// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izxqwwojeawrqhxreqsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eHF3d29qZWF3cnFoeHJlcXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODkxMDQsImV4cCI6MjA3MTE2NTEwNH0.FbBEHzy8yqSRAOluthacXuFcIk5NFZV7pWRBnKIkm8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});